import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-dim': '#c7d5ee',
        'on-secondary-fixed-variant': '#515c70',
        'on-secondary-fixed': '#354053',
        'on-error': '#490106',
        'on-error-container': '#ff9993',
        'surface-container-low': '#09122b',
        'inverse-primary': '#5c5f61',
        'secondary': '#939eb5',
        'on-surface-variant': '#96a9e6',
        'primary-dim': '#b6b9bb',
        'surface-container': '#0a1839',
        'secondary-fixed-dim': '#cad5ed',
        'primary-fixed': '#e0e3e5',
        'surface-variant': '#0a2257',
        'inverse-surface': '#faf8ff',
        'on-primary-fixed': '#3c4042',
        'error': '#ee7d77',
        'error-container': '#7f2927',
        'on-surface': '#dfe4ff',
        'on-tertiary': '#4d5b70',
        'outline-variant': '#32457c',
        'on-primary-container': '#ced1d2',
        'surface-tint': '#c4c7c9',
        'primary': '#c4c7c9',
        'tertiary-fixed-dim': '#c7d5ee',
        'on-background': '#dfe4ff',
        'surface': '#070d1f',
        'on-primary-fixed-variant': '#595c5e',
        'secondary-dim': '#939eb5',
        'on-secondary-container': '#b4c0d7',
        'primary-fixed-dim': '#d2d5d7',
        'primary-container': '#444749',
        'outline': '#6073ad',
        'error-dim': '#bb5551',
        'surface-container-high': '#0b1d48',
        'surface-container-lowest': '#000000',
        'background': '#070d1f',
        'on-tertiary-fixed': '#324054',
        'secondary-container': '#313c4f',
        'surface-container-highest': '#0a2257',
        'tertiary-container': '#d5e3fd',
        'secondary-fixed': '#d8e3fb',
        'on-secondary': '#152032',
        'on-primary': '#3d4142',
        'inverse-on-surface': '#4f5469',
        'tertiary-fixed': '#d5e3fd',
        'tertiary': '#ebf1ff',
        'surface-bright': '#082768',
        'on-tertiary-container': '#455367',
        'surface-dim': '#070d1f',
        'on-tertiary-fixed-variant': '#4e5c71',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      fontFamily: {
        'headline': ['Space Grotesk', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

export default config
